name: Make release

on:
  workflow_dispatch

jobs:
  windows_build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    env:
      VCPKG_PATH: '${{ github.workspace }}/vcpkg'
        
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - uses: lukka/get-cmake@latest
    
    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgJsonGlob: '**/vcpkg.json'
    - name: Run CMake with vcpkg.json manifest(no tests)
      uses: lukka/run-cmake@v10
      with:
        configurePreset: Win-Release
        buildPreset: Win-Release
    - uses: actions/upload-artifact@v3
      with:
        name: AttachA-Win
        path: |
            ${{ github.workspace }}/out/**/AttachA.exe
