name: Run tests on Push

on:
  push

jobs:
    windows_build:
        runs-on: windows-latest
        strategy:
            fail-fast: false
        env:
            VCPKG_PATH: '${{ github.workspace }}/vcpkg'     
        steps:
        - uses: actions/checkout@v3
          with:
            submodules: true
            fetch-depth: 0
        - uses: lukka/get-cmake@latest
        - name: Restore artifacts, or setup vcpkg (do not install any package)
          uses: lukka/run-vcpkg@v10
          with:
            vcpkgJsonGlob: '**/vcpkg.json'
        - name: Run CMake with vcpkg.json manifest(no tests)
          uses: lukka/run-cmake@v10
          with:
            configurePreset: Win-Test
            buildPreset: Win-Test
        - name: Run gtest tests
          run: |
            for test in ${{ github.workspace }}/out/**/AttachATests.exe; do
              "$test"
            done
                
    linux_build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        env:
            VCPKG_PATH: '${{ github.workspace }}/vcpkg'     
        steps:
        - uses: actions/checkout@v3
          with:
            submodules: true
            fetch-depth: 0
        - uses: lukka/get-cmake@latest
        - name: Restore artifacts, or setup vcpkg (do not install any package)
          uses: lukka/run-vcpkg@v10
          with:
            vcpkgJsonGlob: '**/vcpkg.json'
        - name: Run CMake with vcpkg.json manifest(no tests)
          uses: lukka/run-cmake@v10
          with:
            configurePreset: Linux-Test
            buildPreset: Linux-Test
        - name: Run gtest tests
          run: |
            ${{ github.workspace }}/out/build/Linux-Test/tests/AttachATests
                